# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Data Science Projects
tagline:          'CSCI 4831/7000'
description:      'A special topics course at University of Colorado, Boulder.'
url:              http://datascienceprojects.org
baseurl:          /

author:
  name:           'Caleb Phillips'
  url:            http://smallwhitecube.com

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/somerandomsequence/csci-4831-7000-dsp
